# Generated by Django 5.2.7 on 2025-10-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='decricao',
            new_name='descricao',
        ),
    ]
